// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2s_common.proto

#include "c2s_common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace C2S {
PROTOBUF_CONSTEXPR C2SHeartBeat::C2SHeartBeat(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2SHeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2SHeartBeatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2SHeartBeatDefaultTypeInternal() {}
  union {
    C2SHeartBeat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2SHeartBeatDefaultTypeInternal _C2SHeartBeat_default_instance_;
}  // namespace C2S
static ::_pb::Metadata file_level_metadata_c2s_5fcommon_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_c2s_5fcommon_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_c2s_5fcommon_2eproto = nullptr;

const uint32_t TableStruct_c2s_5fcommon_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::C2S::C2SHeartBeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::C2S::C2SHeartBeat, _impl_.state_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::C2S::C2SHeartBeat)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::C2S::_C2SHeartBeat_default_instance_._instance,
};

const char descriptor_table_protodef_c2s_5fcommon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020c2s_common.proto\022\003C2S\"\035\n\014C2SHeartBeat\022"
  "\r\n\005state\030\001 \001(\005*\232\001\n\nC2S_MSG_ID\022\017\n\013MSG_ID_"
  "NONE\020\000\022\025\n\020MSG_ID_HEARTBEAT\020\221N\022\025\n\020MSG_ID_"
  "LOGIN_REQ\020\222N\022\025\n\020MSG_ID_LOGIN_RES\020\223N\022\032\n\025M"
  "SG_ID_LOGIN_ZONE_REQ\020\224N\022\032\n\025MSG_ID_LOGIN_"
  "ZONE_RES\020\225N*\330\001\n\016C2S_ERROR_CODE\022\016\n\nEC_SUC"
  "CESS\020\000\022\025\n\021EC_GENERRAL_ERROR\020e\022\034\n\030EC_SERV"
  "ER_INTERNAL_ERROR\020f\022\027\n\023EC_SERVER_NOT_REA"
  "DY\020g\022\030\n\024EC_INVALID_PARAMETER\020h\022\022\n\016EC_SER"
  "VER_BUSY\020i\022\030\n\024EC_LOGIN_IN_PROGRESS\020j\022 \n\034"
  "EC_LOGIN_SESSION_HAS_EXPIRED\020kb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_c2s_5fcommon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_c2s_5fcommon_2eproto = {
    false, false, 438, descriptor_table_protodef_c2s_5fcommon_2eproto,
    "c2s_common.proto",
    &descriptor_table_c2s_5fcommon_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_c2s_5fcommon_2eproto::offsets,
    file_level_metadata_c2s_5fcommon_2eproto, file_level_enum_descriptors_c2s_5fcommon_2eproto,
    file_level_service_descriptors_c2s_5fcommon_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_c2s_5fcommon_2eproto_getter() {
  return &descriptor_table_c2s_5fcommon_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_c2s_5fcommon_2eproto(&descriptor_table_c2s_5fcommon_2eproto);
namespace C2S {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* C2S_MSG_ID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_c2s_5fcommon_2eproto);
  return file_level_enum_descriptors_c2s_5fcommon_2eproto[0];
}
bool C2S_MSG_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10005:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* C2S_ERROR_CODE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_c2s_5fcommon_2eproto);
  return file_level_enum_descriptors_c2s_5fcommon_2eproto[1];
}
bool C2S_ERROR_CODE_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 106:
    case 107:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class C2SHeartBeat::_Internal {
 public:
};

C2SHeartBeat::C2SHeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:C2S.C2SHeartBeat)
}
C2SHeartBeat::C2SHeartBeat(const C2SHeartBeat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2SHeartBeat* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.state_ = from._impl_.state_;
  // @@protoc_insertion_point(copy_constructor:C2S.C2SHeartBeat)
}

inline void C2SHeartBeat::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.state_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2SHeartBeat::~C2SHeartBeat() {
  // @@protoc_insertion_point(destructor:C2S.C2SHeartBeat)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2SHeartBeat::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2SHeartBeat::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2SHeartBeat::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S.C2SHeartBeat)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.state_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2SHeartBeat::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2SHeartBeat::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:C2S.C2SHeartBeat)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 state = 1;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:C2S.C2SHeartBeat)
  return target;
}

size_t C2SHeartBeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:C2S.C2SHeartBeat)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 state = 1;
  if (this->_internal_state() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2SHeartBeat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2SHeartBeat::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2SHeartBeat::GetClassData() const { return &_class_data_; }


void C2SHeartBeat::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2SHeartBeat*>(&to_msg);
  auto& from = static_cast<const C2SHeartBeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:C2S.C2SHeartBeat)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2SHeartBeat::CopyFrom(const C2SHeartBeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:C2S.C2SHeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2SHeartBeat::IsInitialized() const {
  return true;
}

void C2SHeartBeat::InternalSwap(C2SHeartBeat* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.state_, other->_impl_.state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2SHeartBeat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_c2s_5fcommon_2eproto_getter, &descriptor_table_c2s_5fcommon_2eproto_once,
      file_level_metadata_c2s_5fcommon_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace C2S
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::C2S::C2SHeartBeat*
Arena::CreateMaybeMessage< ::C2S::C2SHeartBeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::C2S::C2SHeartBeat >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
